/* AUTO-GENERATED by scripts/pig/build.py — do not edit. */

export const PIG_SHEET = {
  src: "/sprites/pig/pig-v2.png",
  frameW: 189,
  frameH: 199,
  cols: 12,
  rows: 10,
  totalFrames: 114,
} as const;

export const PIG_CLIPS = {
  idle_breathe: { start: 0, frames: 6, ms: 200, loop: true },
  walk: { start: 6, frames: 8, ms: 120, loop: true },
  walk_letter: { start: 14, frames: 8, ms: 120, loop: true },
  idle_blink: { start: 22, frames: 5, ms: 125, loop: false },
  idle_sniff: { start: 27, frames: 13, ms: 125, loop: false },
  idle_scratch: { start: 40, frames: 9, ms: 140, loop: false },
  idle_letter: { start: 49, frames: 7, ms: 150, loop: true },
  feed: { start: 56, frames: 8, ms: 150, loop: true, chomps: [3, 5] },
  play_chase: { start: 64, frames: 8, ms: 110, loop: true },
  play_bounce: { start: 72, frames: 7, ms: 120, loop: false },
  play_roll: { start: 79, frames: 6, ms: 130, loop: false },
  trick_backflip: { start: 85, frames: 6, ms: 110, loop: false },
  trick_sit: { start: 91, frames: 7, ms: 167, loop: false },
  trick_dance: { start: 98, frames: 7, ms: 130, loop: false },
  pet_enjoy: { start: 105, frames: 4, ms: 160, loop: true },
  pet_end: { start: 109, frames: 5, ms: 150, loop: false },
} as const;

export type PigClip = keyof typeof PIG_CLIPS;
