/* AUTO-GENERATED by scripts/pig/build.py — do not edit. */

export const PIG_SHEET = {
  src: "/sprites/pig/pig-v2.png",
  frameW: 189,
  frameH: 199,
  cols: 12,
  rows: 13,
  totalFrames: 152,
} as const;

export const PIG_CLIPS = {
  idle_breathe: { start: 0, frames: 6, ms: 200, loop: true },
  walk: { start: 6, frames: 8, ms: 120, loop: true },
  walk_letter: { start: 14, frames: 8, ms: 120, loop: true },
  idle_blink: { start: 22, frames: 5, ms: 125, loop: false },
  idle_sniff: { start: 27, frames: 13, ms: 125, loop: false },
  idle_look: { start: 40, frames: 13, ms: 125, loop: false },
  idle_scratch: { start: 53, frames: 9, ms: 140, loop: false },
  idle_sad: { start: 62, frames: 5, ms: 200, loop: true },
  idle_hungry: { start: 67, frames: 5, ms: 180, loop: true },
  idle_letter: { start: 72, frames: 7, ms: 150, loop: true },
  feed_munch: { start: 79, frames: 8, ms: 150, loop: true, chomps: [3, 5] },
  feed_gobble: { start: 87, frames: 8, ms: 150, loop: true, chomps: [2, 4, 6] },
  play_chase: { start: 95, frames: 8, ms: 110, loop: true },
  play_bounce: { start: 103, frames: 7, ms: 120, loop: false },
  play_roll: { start: 110, frames: 6, ms: 130, loop: false },
  trick_spin: { start: 116, frames: 7, ms: 90, loop: false },
  trick_backflip: { start: 123, frames: 6, ms: 110, loop: false },
  trick_sit: { start: 129, frames: 7, ms: 167, loop: false },
  trick_dance: { start: 136, frames: 7, ms: 130, loop: false },
  pet_enjoy: { start: 143, frames: 4, ms: 160, loop: true },
  pet_end: { start: 147, frames: 5, ms: 150, loop: false },
} as const;

export type PigClip = keyof typeof PIG_CLIPS;
