/* AUTO-GENERATED by scripts/pig/build.py — do not edit. */

export const PIG_SHEET = {
  src: "/sprites/pig/pig-v2.png",
  frameW: 189,
  frameH: 199,
  cols: 12,
  rows: 12,
  totalFrames: 134,
} as const;

export const PIG_CLIPS = {
  idle_breathe: { start: 0, frames: 6, ms: 200, loop: true },
  walk: { start: 6, frames: 8, ms: 120, loop: true },
  idle_blink: { start: 14, frames: 5, ms: 125, loop: false },
  idle_sniff: { start: 19, frames: 13, ms: 125, loop: false },
  idle_look: { start: 32, frames: 13, ms: 125, loop: false },
  idle_scratch: { start: 45, frames: 9, ms: 140, loop: false },
  idle_sad: { start: 54, frames: 5, ms: 200, loop: true },
  idle_hungry: { start: 59, frames: 5, ms: 180, loop: true },
  idle_letter: { start: 64, frames: 7, ms: 150, loop: true },
  feed_munch: { start: 71, frames: 8, ms: 150, loop: true, chomps: [3, 5] },
  feed_gobble: { start: 79, frames: 8, ms: 150, loop: true, chomps: [2, 4, 6] },
  play_chase: { start: 87, frames: 4, ms: 110, loop: true },
  play_bounce: { start: 91, frames: 5, ms: 120, loop: false },
  play_roll: { start: 96, frames: 6, ms: 130, loop: false },
  trick_spin: { start: 102, frames: 7, ms: 90, loop: false },
  trick_backflip: { start: 109, frames: 6, ms: 110, loop: false },
  trick_sit: { start: 115, frames: 5, ms: 150, loop: false },
  trick_dance: { start: 120, frames: 5, ms: 130, loop: false },
  pet_enjoy: { start: 125, frames: 4, ms: 160, loop: true },
  pet_end: { start: 129, frames: 5, ms: 150, loop: false },
} as const;

export type PigClip = keyof typeof PIG_CLIPS;
