"""Pack downloaded PixelLab clips into the atlas + typed manifest.

    python3 scripts/pig/build.py

Outputs:
  public/sprites/pig/pig-v2.png
  src/lib/pig-anim.generated.ts
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).parent))
from frame import ATLAS_COLS, FRAME_H, FRAME_W  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
JOBS = ROOT / "assets" / "pixellab" / "jobs.json"
CLIPS_DIR = ROOT / "assets" / "pixellab" / "clips"
ATLAS_PATH = ROOT / "public" / "sprites" / "pig" / "pig-v2.png"
MANIFEST_PATH = ROOT / "src" / "lib" / "pig-anim.generated.ts"

# Prefer this order in the atlas so early indices stay stable as clips are added.
CLIP_ORDER = [
    "idle_breathe",
    "walk",
    "idle_blink",
    "idle_sniff",
    "idle_look",
    "idle_scratch",
    "idle_sad",
    "idle_hungry",
    "idle_letter",
    "feed",
    "play_chase",
    "play_bounce",
    "play_roll",
    "trick_spin",
    "trick_backflip",
    "trick_sit",
    "trick_dance",
    "pet_enjoy",
    "pet_end",
]


def fit_frame(im: Image.Image) -> Image.Image:
    """Centre the sprite on the contract canvas, feet toward the bottom."""
    im = im.convert("RGBA")
    canvas = Image.new("RGBA", (FRAME_W, FRAME_H), (0, 0, 0, 0))
    # Scale down only if a generation came back larger; never upscale.
    w, h = im.size
    if w > FRAME_W or h > FRAME_H:
        scale = min(FRAME_W / w, FRAME_H / h)
        im = im.resize((max(1, int(w * scale)), max(1, int(h * scale))), Image.NEAREST)
        w, h = im.size
    x = (FRAME_W - w) // 2
    y = FRAME_H - h  # register to bottom (ground)
    canvas.paste(im, (x, y), im)
    return canvas


def load_clip_frames(name: str) -> list[Image.Image]:
    folder = CLIPS_DIR / name
    if not folder.exists():
        return []
    files = sorted(folder.glob("frame-*.png"))
    return [fit_frame(Image.open(f)) for f in files]


def ensure_idle_fallback() -> list[Image.Image]:
    """If idle_breathe isn't ready, seed a 1-frame idle from the shipped PNG."""
    src = ROOT / "public" / "sprites" / "pig-idle.png"
    return [fit_frame(Image.open(src))]


def main() -> None:
    meta = json.loads(JOBS.read_text()) if JOBS.exists() else {"clips": {}}
    clip_meta = meta.get("clips", {})

    packed: list[tuple[str, list[Image.Image], dict]] = []
    for name in CLIP_ORDER:
        frames = load_clip_frames(name)
        info = clip_meta.get(name, {})
        if not frames and name == "idle_breathe":
            frames = ensure_idle_fallback()
            info = {**info, "ms": 166, "loop": True, "frames": 1}
        if not frames:
            continue
        packed.append((name, frames, info))

    if not packed:
        raise SystemExit("no clips to pack — run download_clips.py first")

    total = sum(len(f) for _, f, _ in packed)
    cols = ATLAS_COLS
    rows = (total + cols - 1) // cols
    atlas = Image.new("RGBA", (cols * FRAME_W, rows * FRAME_H), (0, 0, 0, 0))

    manifest_clips: dict[str, dict] = {}
    cursor = 0
    for name, frames, info in packed:
        start = cursor
        for frame in frames:
            col, row = cursor % cols, cursor // cols
            atlas.paste(frame, (col * FRAME_W, row * FRAME_H), frame)
            cursor += 1
        ms = int(info.get("ms", 125))
        loop = bool(info.get("loop", False))
        manifest_clips[name] = {
            "start": start,
            "frames": len(frames),
            "ms": ms,
            "loop": loop,
            # Frames the scene can hang effects off, e.g. crumbs on a chew.
            "chomps": [int(i) for i in info.get("chomps", [])],
        }

    ATLAS_PATH.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(ATLAS_PATH)
    print(f"atlas {atlas.size[0]}×{atlas.size[1]} ({total} frames) → {ATLAS_PATH}")

    lines = [
        "/* AUTO-GENERATED by scripts/pig/build.py — do not edit. */",
        "",
        "export const PIG_SHEET = {",
        '  src: "/sprites/pig/pig-v2.png",',
        f"  frameW: {FRAME_W},",
        f"  frameH: {FRAME_H},",
        f"  cols: {cols},",
        f"  rows: {rows},",
        f"  totalFrames: {total},",
        "} as const;",
        "",
        "export const PIG_CLIPS = {",
    ]
    for name, clip in manifest_clips.items():
        loop = "true" if clip["loop"] else "false"
        chomps = f", chomps: [{', '.join(str(i) for i in clip['chomps'])}]" if clip["chomps"] else ""
        lines.append(
            f"  {name}: {{ start: {clip['start']}, frames: {clip['frames']}, "
            f"ms: {clip['ms']}, loop: {loop}{chomps} }},"
        )
    lines += [
        "} as const;",
        "",
        "export type PigClip = keyof typeof PIG_CLIPS;",
        "",
    ]
    MANIFEST_PATH.write_text("\n".join(lines))
    print(f"manifest → {MANIFEST_PATH}")
    print("clips:", ", ".join(manifest_clips))


if __name__ == "__main__":
    main()
